jupyterhub:
  hub:
    annotations:
      argocd.argoproj.io/health: "Healthy"
    db:
      pvc:
        storageClassName: nfs-atlas
  
  proxy:
    annotations:
      argocd.argoproj.io/health: "Healthy"

    podSecurityContext:
      runAsNonRoot: true
      fsGroup: 1000

  singleuser:
    storage:
      dynamic:
        storageClass: nfs-atlas
