jupyterhub:
  hub:
    # annotations:
    #   argocd.argoproj.io/health: "Healthy"
    db:
      pvc:
        storageClassName: nfs-atlas
        storage: 8Gi

    podSecurityContext:
      runAsNonRoot: true
      fsGroup: 1000
  
  # proxy:
  #   annotations:
  #     argocd.argoproj.io/health: "Healthy"


  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false

  singleuser:
    storage:
      dynamic:
        storageClass: nfs-atlas
