jupyterhub:
  hub:
    db:
      pvc:
        storageClassName: nfs-atlas

    podSecurityContext:
      runAsNonRoot: true
      fsGroup: 1000

  singleuser:
    storage:
      dynamic:
        storageClass: nfs-atlas
